import { join } from "node:path";
import { loadData, PACKAGE_ROOT } from "../src/data.ts";
import { loadTuning } from "../src/tuning.ts";
import { buildGraph } from "../src/graph.ts";
import { emitInk } from "../src/ink.ts";
import { emitStoryJson } from "../src/story.ts";
import { resolveWeek, seedThreadsFromContent } from "../src/week.ts";
import { searchReachable } from "../src/walk.ts";
const DATA_DIR = join(PACKAGE_ROOT, "data");
const data = loadData(DATA_DIR, []);
const tuning = loadTuning(DATA_DIR, []);
const graph = buildGraph(data, tuning);
const storyJson = emitStoryJson(emitInk(graph));
const days = resolveWeek(data, { slot:1, life:1, picked_location:"town", threads:[], lead_pool:["LEAD-01","LEAD-02","LEAD-03"], aliveness_band:"quiet" } as any, tuning, { seedThreads: seedThreadsFromContent(data) });
const t0 = Date.now();
const r = searchReachable({ storyJson, graph, days }, { maxScenePaths:20_000, maxSceneDepth:60, maxWeeks:10, maxSteps:5_000, maxMillis:120_000 });
console.log("search ms", Date.now()-t0, "weeks", r.bounds.weeksWalked);
const targets=["SC-F1-03","SC-T2-11","SC-T2-21","SC-T2-23"];
for(const t of targets) console.log(t, r.reachableScenes.includes(t) ? "REACHED" : "*** MISSING");
console.log("unreached scenes:", graph.scenes.map(s=>s.scene_id).filter(id=>!r.reachableScenes.includes(id)));
console.log("bounds.hit", r.bounds.hit);
console.log("unexplored", r.bounds.unexploredScenes);
